export const LOGOUT='LOGOUT';
export const LOGIN='LOGIN';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';


export const SIGNUP='SIGNUP'
export const SIGNUP_SUCCESS='SIGN_SUCCESS';
export const SIGNUP_FAILURE='SIGNUP_FAILURE';

export const FORGET='FORGET'
export const FORGET_SUCCESS='FORGET_SUCCESS';
export const FORGET_FAILURE='FORGET_FAILURE';

export const USER_DATA='USER_DATA';
export const USER_DATA_SUCCESS='USER_DATA_SUCCESS';
export const USER_DATA_FAILURE='USER_DATA_FAILURE';

export const SIDEBAR_TOGGLE='SIDEBAR_TOGGLE';

// Customer
export const CUSTOMER_GET= 'CUSTOMER_GET';
export const CUSTOMER_GET_SUCCESS= 'CUSTOMER_GET_SUCCESS';
export const CUSTOMER_GET_FAILURE= 'CUSTOMER_GET_FAILURE';

export const CUSTOMER_UPDATE= 'CUSTOMER_UPDATE';
export const CUSTOMER_UPDATE_SUCCESS= 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILURE= 'CUSTOMER_UPDATE_FAILURE';

export const CUSTOMER_ADD= 'CUSTOMER_ADD';
export const CUSTOMER_ADD_SUCCESS= 'CUSTOMER_ADD_SUCCESS';
export const CUSTOMER_ADD_FAILURE= 'CUSTOMER_ADD_FAILURE';

export const CUSTOMER_HISTORY= 'CUSTOMER_HISTORY';
export const CUSTOMER_HISTORY_SUCCESS= 'CUSTOMER_HISTORY_SUCCESS';
export const CUSTOMER_HISTORY_FAILURE= 'CUSTOMER_HISTORY_FAILURE';

export const CUSTOMER_HISTORY_DETAILS= 'CUSTOMER_DETAILS_HISTORY';
export const CUSTOMER_HISTORY_DETAILS_SUCCESS= 'CUSTOMER_HISTORY_DETAILS_SUCCESS';
export const CUSTOMER_HISTORY_DETAILS_FAILURE= 'CUSTOMER_HISTORY_DETAILS_FAILURE';



// Pay
export const PAY_AMOUNT= 'PAY_AMOUNT';
export const PAY_AMOUNT_SUCCESS= 'PAY_AMOUNT_SUCCESS';
export const PAY_AMOUNT_FAILURE= 'PAY_AMOUNT_FAILURE';



// PRODUCT
export const PRODUCT_GET= 'PRODUCT_GET';
export const PRODUCT_GET_SUCCESS= 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAILURE= 'PRODUCT_GET_FAILURE';

export const PRODUCT_UPDATE= 'PRODUCT_UPDATE';
export const PRODUCT_UPDATE_SUCCESS= 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE= 'PRODUCT_UPDATE_FAILURE';

export const PRODUCT_ADD= 'PRODUCT_ADD';
export const PRODUCT_ADD_SUCCESS= 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAILURE= 'PRODUCT_ADD_FAILURE';

export const PRODUCT_TOGGLE= 'PRODUCT_TOGGLE';
export const PRODUCT_TOGGLE_SUCCESS= 'PRODUCT_TOGGLE_SUCCESS';
export const PRODUCT_TOGGLE_FAILURE= 'PRODUCT_TOGGLE_FAILURE';

export const CUSTOMER_SET= 'CUSTOMER_SET';
export const SUPPLIER_SET= 'SUPPLIER_SET';

export const PRODUCT_SET= 'PRODUCT_SET';

export const ACTIVE_PRODUCT_GET= 'ACTIVE_PRODUCT_GET';
export const ACTIVE_PRODUCT_GET_SUCCESS= 'ACTIVE_PRODUCT_GET_SUCCESS';
export const ACTIVE_PRODUCT_GET_FAILURE= 'ACTIVE_PRODUCT_GET_FAILURE';

export const ADD_TO_CART= 'ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';

export const CART= 'CART';
export const CART_SUCCESS= 'CART_SUCCESS';
export const CART_FAILURE= 'CART_FAILURE';

export const CUSTOMER_DASHBOARD= 'CUSTOMER_DASHBOARD';
export const CUSTOMER_DASHBOARD_SUCCESS= 'CUSTOMER_DASHBOARD_SUCCESS';
export const CUSTOMER_DASHBOARD_FAILURE= 'CUSTOMER_DASHBOARD_FAILURE';

export const SUPPLIER_DASHBOARD= 'SUPPLIER_DASHBOARD';
export const SUPPLIER_DASHBOARD_SUCCESS= 'SUPPLIER_DASHBOARD_SUCCESS';
export const SUPPLIER_DASHBOARD_FAILURE= 'SUPPLIER_DASHBOARD_FAILURE';

export const UPDATE_CART= 'UPDATE_CART';






// Supplier
export const SUPPLIER_GET= 'SUPPLIER_GET';
export const SUPPLIER_GET_SUCCESS= 'SUPPLIER_GET_SUCCESS';
export const SUPPLIER_GET_FAILURE= 'SUPPLIER_GET_FAILURE';

export const SUPPLIER_UPDATE= 'SUPPLIER_UPDATE';
export const SUPPLIER_UPDATE_SUCCESS= 'SUPPLIER_UPDATE_SUCCESS';
export const SUPPLIER_UPDATE_FAILURE= 'SUPPLIER_UPDATE_FAILURE';

export const SUPPLIER_ADD= 'SUPPLIER_ADD';
export const SUPPLIER_ADD_SUCCESS= 'SUPPLIER_ADD_SUCCESS';
export const SUPPLIER_ADD_FAILURE= 'SUPPLIER_ADD_FAILURE';

export const SUPPLIER_HISTORY= 'SUPPLIER_HISTORY';
export const SUPPLIER_HISTORY_SUCCESS= 'SUPPLIER_HISTORY_SUCCESS';
export const SUPPLIER_HISTORY_FAILURE= 'SUPPLIER_HISTORY_FAILURE';

export const SUPPLIER_HISTORY_DETAILS= 'SUPPLIER_DETAILS_HISTORY';
export const SUPPLIER_HISTORY_DETAILS_SUCCESS= 'SUPPLIER_HISTORY_DETAILS_SUCCESS';
export const SUPPLIER_HISTORY_DETAILS_FAILURE= 'SUPPLIER_HISTORY_DETAILS_FAILURE';

// Pay
export const PAY_AMOUNT_SUPPLIER= 'PAY_AMOUNT_SUPPLIER';
export const PAY_AMOUNT_SUPPLIER_SUCCESS= 'PAY_AMOUNT_SUPPLIER_SUCCESS';
export const PAY_AMOUNT_SUPPLIER_FAILURE= 'PAY_AMOUNT_SUPPLIER_FAILURE';


// Customer Report
export const CUSTOMER_REPORT= 'CUSTOMER_REPORT';
export const CUSTOMER_REPORT_SUCCESS= 'CUSTOMER_REPORT_SUCCESS';
export const CUSTOMER_REPORT_FAILURE= 'CUSTOMER_REPORT_FAILURE';

// Supplier Report
export const SUPPLIER_REPORT= 'SUPPLIER_REPORT';
export const SUPPLIER_REPORT_SUCCESS= 'SUPPLIER_REPORT_SUCCESS';
export const SUPPLIER_REPORT_FAILURE= 'SUPPLIER_REPORT_FAILURE';















